### ISSUE TITLE
Unable to parse account response with exotic signers.

### ISSUE THREAD

**Issue by Synesso** [Synesso/scala-stellar-sdk#45]
e.g. `GACZHAQLFECAHDSFDQPCOAD6ITVWR7BUZAIRRUGOAPLECX74O6222A4G` on test network, which has 

```
"signers":[{
    "public_key":"XAJDCI5LCIYSHKYSGER2WERREOVREMJDVMJDCI5LCIYSHKYSGER2WOFC",
    "weight":1,
    "key":"XAJDCI5LCIYSHKYSGER2WERREOVREMJDVMJDCI5LCIYSHKYSGER2WOFC",
    "type":"sha256_hash"
  },{
    "public_key":"TDX66CQK57XQUCXP54FAV37PBIFO73YKBLX66CQK57XQUCXP54FAVOGL",
    "weight":1,
    "key":"TDX66CQK57XQUCXP54FAV37PBIFO73YKBLX66CQK57XQUCXP54FAVOGL",
    "type":"preauth_tx"
  },{
    "public_key":"GACZHAQLFECAHDSFDQPCOAD6ITVWR7BUZAIRRUGOAPLECX74O6222A4G",
    "weight":1,
    "key":"GACZHAQLFECAHDSFDQPCOAD6ITVWR7BUZAIRRUGOAPLECX74O6222A4G",
    "type":"ed25519_public_key"
  }]
```

exception being 

```
Caused by: stellar.sdk.FormatException: null
	at stellar.sdk.StrKey$.decodeCheck(StrKey.scala:54)
	at stellar.sdk.StrKey$.decodeStellarAccountId(StrKey.scala:34)
	at stellar.sdk.KeyPair$.fromAccountId(KeyPair.scala:202)
	at stellar.sdk.resp.AccountRespDeserializer$$anonfun$$lessinit$greater$1.$anonfun$new$5(AccountResp.scala:58)
	at scala.collection.immutable.List.map(List.scala:283)
	at stellar.sdk.resp.AccountRespDeserializer$$anonfun$$lessinit$greater$1.apply(AccountResp.scala:56)

```

**Comment by Synesso** [comment]
Fixed in v0.6.2
